stages:
- test
- publish
- example-app-test

cache:
  key: "$CI_PIPELINE_ID"
  untracked: true

test:
  stage: test
  script:
    - sbt clean update test

artifact-publish:
  stage: publish
  script: 
    - sbt publish

test-example-application:
  services:
    - docker:dind
  stage: example-app-test
  script:
    - cd examples/gestalt-framework-auth
    - ./test-with-docker.sh

github-publish:
  stage: publish
  script: 
    - git remote remove github || true
    - git remote add github https://$GITHUB_CREDENTIALS@github.com/GalacticFog/gestalt-security-play.git
    - |
      if [ -z ${CI_BUILD_TAG+x} ]; then 
         git push github HEAD:$CI_BUILD_REF_NAME
      else 
         git push -f github $CI_BUILD_TAG
      fi
  only:
    - master
    - tags

